/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.ch02;

import org.junit.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import static org.junit.Assert.*;

public class AppTest {
    private static Logger logger = LoggerFactory.getLogger(AppTest.class);
    private static AnnotationConfigApplicationContext appContext;

    @BeforeClass
    public static void setUp() {
        appContext = new AnnotationConfigApplicationContext(AppContext.class);
    }

    @AfterClass
    public static void tearDown() {
        logger.info("class destroyed");
    }

    @Test
    public void 싱글톤_객체가_같음을_확인() {
        Greeter g1 = appContext.getBean(Greeter.class);
        Greeter g2 = appContext.getBean(Greeter.class);
        assertEquals(g1, g2);
    }

    @Test
    public void 싱글톤_객체가_다름을_확인() {
        SayHello s1 = appContext.getBean("helloOnce", SayHello.class);
        SayHello s2 = appContext.getBean("helloTwice", SayHello.class);
        assertNotEquals(s1, s2);
    }
}
